# Generated by Django 4.2.6 on 2023-11-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0003_rename_regestration_createregister_delete_leader_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createregister',
        ),
    ]
