# Generated by Django 4.2.6 on 2023-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0004_delete_createregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='createregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('adharnumber', models.CharField(max_length=14)),
                ('educationalqualificatiom', models.CharField(choices=[('SSC', 'SSC'), ('Intermediate', 'Intermediate'), ('U.G', 'U.G'), ('P.G', 'P.G'), ('Ph.D', 'Ph.D'), ('None', 'None')], max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=20)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('INDIA', 'INDIA'), ('INDIA', 'INDIA')], max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=20)),
                ('postalcode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'createregister_table',
            },
        ),
    ]
