# Generated by Django 4.2.6 on 2023-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0005_createregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio_data', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
