# Generated by Django 4.2.6 on 2023-11-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0006_candidatein_delete_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio_data', models.CharField(max_length=500)),
            ],
        ),
    ]
