# Generated by Django 4.2.5 on 2023-11-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0007_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='bio_data',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='name',
        ),
        migrations.AlterModelTable(
            name='leader',
            table='Leader_table',
        ),
    ]
