# Generated by Django 4.2.5 on 2023-11-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0008_remove_leader_bio_data_remove_leader_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leader',
            table=None,
        ),
    ]
